"""add_subject_id_to_posts

Revision ID: 037cc9dc5eb9
Revises: 0002_subjects
Create Date: 2026-03-14 17:42:11.117961
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037cc9dc5eb9'
down_revision = '0002_subjects'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_subject_id'), 'posts', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_subject_id'), table_name='posts')
    op.drop_column('posts', 'subject_id')
    # ### end Alembic commands ###
